version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: web
      POSTGRES_PASSWORD: web-password
      POSTGRES_DB: CustomersDB
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
